### ISSUE TITLE
Course structure: wrong import statements

### ISSUE THREAD

**Issue by a-a-hofmann** [mp-access/Course-Service#118]
Private/public test suite import statements are wrong
We need to change the import statements to match course structure repo directory structure and change the backend to create the current folder names as in the repo so that the imports will work

```
testSuite (unittest.loader._FailedTest) ... ERROR

testSuite2 (unittest.loader._FailedTest) ... ERROR

======================================================================

ERROR: testSuite (unittest.loader._FailedTest)

----------------------------------------------------------------------

ImportError: Failed to import test module: testSuite

Traceback (most recent call last):

File "/usr/local/lib/python3.8/unittest/loader.py", line 436, in _find_test_path

module = self._get_module_from_name(name)

File "/usr/local/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name

__import__(name)

File "/usr/src/test/testSuite.py", line 3, in <module>

from solution_files.task_1 import Aircraft, IntercontinentalAircraft, ShortHaulAircraft, ControlTower

ModuleNotFoundError: No module named 'solution_files'

======================================================================

ERROR: testSuite2 (unittest.loader._FailedTest)

----------------------------------------------------------------------

ImportError: Failed to import test module: testSuite2

Traceback (most recent call last):

File "/usr/local/lib/python3.8/unittest/loader.py", line 436, in _find_test_path

module = self._get_module_from_name(name)

File "/usr/local/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name

__import__(name)

File "/usr/src/test/testSuite2.py", line 3, in <module>

from solution_files.task_1 import Aircraft, IntercontinentalAircraft, ShortHaulAircraft, ControlTower

ModuleNotFoundError: No module named 'solution_files'

----------------------------------------------------------------------

Ran 2 tests in 0.001s

FAILED (errors=2)

>
```

**Comment by a-a-hofmann** [comment]
I've fixed this exercise but the others also need fixing:
https://github.com/mp-access/course_structure/tree/master/assignment_01/exercise_01
